language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t rwansing/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rwansing/docker-react npm run test